### ISSUE TITLE
HTTP_PROPFIND, HTTPPROPPATCH, etc not declared??

### ISSUE THREAD

**Issue by jake-code** [rostwolke/ESPAsyncWebdav#1]
Hi, I just noticed your library and was trying to test the included example (simple) but I cannot even get it to build. I get errors on HTTP_PROPFIND, HTTP_PROPPATCH, etc not being declared??
Am I missing some other supporting library? I searched every file in the arduino directories for these declarations and nothing was found.

**Comment by rostwolke** [comment]
Hi,

I totally forgot to mention in the readme that you need a patched version of ESPAsyncWebServer. You can either use my fork of the library or apply my PR in the original repository on your code.

I will update the README.md as soon as possible. Edit: I updated the readme.

**Comment by jake-code** [comment]
Hi, thanks for the reply. I'll take a look at the patches you mention.

**Comment by jake-code** [comment]
I noticed that there is an error with your request to have your patch committed to the ESPAsyncWebServer base. Do you think you will have this resolved shortly?

**Comment by jake-code** [comment]
Sorry clicked the close by mistake

**Comment by rostwolke** [comment]
Hi, what do you mean? In my first commit I had an error but I fixed it in the second commit.

**Comment by jake-code** [comment]
Hi, It seemed like that to me, but when I updated my local copy of the ESPAsyncWebServer code and didn't find the changes I then looked at the code directly on github and your patch does not seem to be applied/commited. So I assumed there was still an error. Am I missing something here?

**Comment by rostwolke** [comment]
The patch is only merged in my fork of the repository. In the original repository it has not yet been accepted (and might never be). It seems to me like me-no-dev, the original author, recently is not active.

To make this project work just clone/download this repo:
https://github.com/rostwolke/ESPAsyncWebServer

It not only includes my patch but also another fix for a memory leak and is up to date.

**Comment by jake-code** [comment]
Ok, that explains it as I was looking at you request to merge into the original repo.
Thanks for bearing with me on this. I think the situation is now more than clear and of helpl to others that may have the same problem so I'm going to close the issue as resolved.
